<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goodsService.proto

namespace Grpc\Goods;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grpc.goods.GetGoodsResponse</code>
 */
class GetGoodsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string goods_name = 1;</code>
     */
    protected $goods_name = '';
    /**
     * Generated from protobuf field <code>int32 goods_price = 2;</code>
     */
    protected $goods_price = 0;
    /**
     * Generated from protobuf field <code>int32 id = 3;</code>
     */
    protected $id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $goods_name
     *     @type int $goods_price
     *     @type int $id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GoodsService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string goods_name = 1;</code>
     * @return string
     */
    public function getGoodsName()
    {
        return $this->goods_name;
    }

    /**
     * Generated from protobuf field <code>string goods_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGoodsName($var)
    {
        GPBUtil::checkString($var, True);
        $this->goods_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 goods_price = 2;</code>
     * @return int
     */
    public function getGoodsPrice()
    {
        return $this->goods_price;
    }

    /**
     * Generated from protobuf field <code>int32 goods_price = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGoodsPrice($var)
    {
        GPBUtil::checkInt32($var);
        $this->goods_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 id = 3;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

}

